---
project_name: progen
before:
  hooks:
    - go mod download

builds:
  - main: ./main.go
    binary: progen
    ldflags:
      - -s -w -X github.com/kozmod/progen/internal.Version=v{{.Version}}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - linux_arm
      - windows_amd64
archives:
  - files:
      - Readme.md
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch