---
project_name: progen
before:
  hooks:
    - go mod download
builds:
  - main: ./main.go
    binary: progen
    ldflags:
      - -s -w -X github.com/kozmod/progen/internal.Version=v{{.Version}}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
archives:
  - files:
      - Readme.md
      - LICENSE
checksum:
  name_template: "checksum.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc