---
project_name: progen
before:
  hooks:
    - go mod download
builds:
  - main: ./main.go
    binary: progen
    ldflags:
      - -s -w -X github.com/kozmod/progen/internal.Version=v{{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README.md
      - LICENSE
checksum:
  name_template: "checksum.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc